export const GET_CITIES = "GET_CITIES";
export const GET_ITINERARIES = "GET_ITINERARIES";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
